### ISSUE TITLE
Allow custom path to db file

### ISSUE THREAD

**Issue by cmwg71** [QuiteRSS/quiterss#1526] opened 2022-02-24 14:48 UTC
Hi folks,
love quiterss, but i use it across multiple PCs (home / work / travel) and would like to be able to move the feed db to a custom path, in order for it to sync across devices (by placing it into ie. onedrive). This would allow for an easy sync of current read/unread feeds when going to the next device. 
regards
Christian

**Comment by arhohryakov** [comment] 2022-02-25 01:28
You can use portable version and sync whole app folder.

**Comment by shuvashish76** [comment] 2022-03-04 15:45
> You can use portable version and sync whole app folder.

For Windows users I guess. But what about Linux users?

**Comment by cmwg71** [comment] 2022-03-04 16:45
> You can use portable version and sync whole app folder.

sadly it does not work (on windows), i have tried with OneDrive / Nextcloud and neither work. 
If you sync the whole portable folder with it in it, and start it on another machine, it does not retain feeds nor what has been read or not. 

The function of it being able to sync feeds / read status would be key for a proper sync between PCs.

**Comment by arhohryakov** [comment] 2022-03-05 06:39
> For Windows users I guess. But what about Linux users?

You can setup your sync tool with only 2 files: Database file and Settings file.

Path to these files you can find here:  
![image](https://user-images.githubusercontent.com/4505544/156871726-27448bc7-47ab-4442-9672-4722c21dd982.png)

**Comment by arhohryakov** [comment] 2022-03-05 06:54
> sadly it does not work (on windows)

Maybe you are trying to sync while app is working and you are using the option "Store DB in memory". Anyway, it is not related to the issue.

**Comment by arhohryakov** [comment] 2022-03-05 06:57
Duplicate of #1123

**Closed as completed by arhohryakov** 2022-03-05 06:57 UTC
Labels: feature
