### ISSUE TITLE
Deleted Posts Get Reloaded

### ISSUE THREAD

**Issue by dave47** [QuiteRSS/quiterss#1033] opened 2017-12-23 16:31 UTC
When I delete posts they soon get reloaded. Once I delete a post I do not want to see it again.

l am using Cleanup Deleted.

How do I get this behavior to stop?

**Comment by Katarn** [comment] 2017-12-24 18:28
Duplicate of #949 #974
By the way, here is the answer: https://github.com/QuiteRSS/quiterss/issues/974#issuecomment-308781869

**Closed as completed** 2018-01-01 12:30 UTC
