### ISSUE TITLE
quiterss: qGetPtrHelper<QScopedPointer<QObjectData> >(): quiterss killed by SIGSEGV

### ISSUE THREAD

**Issue by Pupkur** [QuiteRSS/quiterss#1168] opened 2019-05-20 08:15 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1705569

**Comment by TheDcoder** [comment] 2019-05-28 05:05
I suggest changing the title to be more generic as I am getting a different but similar error upon crashing, I propose "QuiteRSS crashing in Fedora 30" (since it seems to have started crashing after the upgrade). Once the devs have confirmed the issue we can go with a more technically accurate title :slightly_smiling_face:

I have also created a related thread on Ask Fedora: https://ask.fedoraproject.org/t/quiterss-crashing-after-upgrade-to-fedora-30/1349

**Comment by feed21** [comment] 2019-06-16 09:38
I am getting something similar, my syslog reports random crashes to quiterss:
`QNetworkAccessM[26902]: segfault at 0 ip 00007f97048040d4 sp 00007f9678ffb718 error 4 in libQt5Network.so.5.9.5[7f9704770000+183000]`

Is this related?

I am using Ubuntu 18.04

Also something similar here: https://github.com/QuiteRSS/quiterss/issues/1175

**Comment by feed21** [comment] 2019-06-24 11:06
I have found out that this is an issue from qt5 not from QuiteRSS, a fix has been released and should be in all your repo's soon when you upgrade your distro packages.

Issue reported here: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1833536

You may close this issue here now.

**Closed as completed** 2019-11-21 04:02 UTC
