### ISSUE TITLE
URL corrupting - removing slash

### ISSUE THREAD

**Issue by Nama** [QuiteRSS/quiterss#1108] opened 2018-08-16 00:38 UTC
Hi,

I have trouble to add one specific rss. Rest is working fine. The rss needs authentication. Even with credentials, the same error appears (of course, the domain in the error is wrong, one slash is gone).
FreshRSS is the server and adding the rss from the [demo](https://demo.freshrss.org/i/?a=rss&hours=168) works.
![grafik](https://user-images.githubusercontent.com/2297270/44180484-fa84a580-a0fc-11e8-9137-3c42503a3c31.png)

**Comment by Katarn** [comment] 2018-11-26 18:52
The link that is shown in the screenshot, it does not work. It redirects to the address ".?c=error", which is obviously wrong.

```bash
curl "https://rss.tastyespresso.de/p/i/?a=rss&hours=168" -vvv
...
< HTTP/1.1 302 Moved Temporarily
...
< Location: .?c=error
```

**Comment by genodeftest** [comment] 2018-11-26 22:17
In other words: This is not a bug in QuiteRSS but in the website you are using. You should report the issue to the webmaster instead and close this issue here.

**Comment by Nama** [comment] 2018-11-26 22:36
You guys realize it's been over 3 months ago?
The link is offline and doesn't work anymore. But worked then.
I suggest you check your link parser. I switched to tt-rss in the meantime.

Was it really needed that two people tell me this?

**Comment by Katarn** [comment] 2018-11-27 10:18
With the parser, everything is fine, an error in the script on the site. However, I improved the definition of such situations. Let's not be rude, here is no paid round-the-clock technical support. Thanks for the information about the problem.

**Comment by Nama** [comment] 2018-11-27 10:37
Sorry, your assuming that I tried to add dead links didn't make me happy x)

The webserver didn't have any redirections. The site used to work on the browser (as .de/p/, without redirecting to .dep/).
So I'm not sure that the new commit would fix this issue.

**Comment by Katarn** [comment] 2018-11-27 11:18
I gave an example of the headers given by the server above. It redirects to ```.?c=error```, but correctly so: ```./?c=error```

Yes, the problem with access to the feed does not fix it, but the application will now display a ```Server replied: Not Found!``` message, and inside the application the link will be converted to ```https://rss.tastyespresso.de/p/i/?c=error``` - without ```dep```. This url returns 404 code.

**Closed as completed** 2023-07-28 14:19 UTC
